project:
  type: book
  output-dir: docs

book:
  title: "Analisis del Cambio Climático con R"
  author: "Junior Ponce"
  date: "today"
  chapters:
    - index.qmd
    - intro.qmd
    - visualizaciones.qmd
    - mapas.qmd
    - proyecciones.qmd
    - conclusiones.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true

